version: 2

updates:

  - package-ecosystem: "npm"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "[npm] "
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
