changelog:
  categories:
    - title: New features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - no-release-note
    - title: Dependencies
      labels:
        - dependencies
