name: Missing translations
description: Request translations for another language
labels: [ "translation" ]
body:
  - type: input
    id: language-name
    attributes:
      label: Language name
    validations:
      required: true
  - type: input
    id: language-code
    attributes:
      label: Language code (LCID)
    validations:
      required: false
