name: Translation issue
description: Request a fix for a translation.
labels: [ "translation" ]
body:
  - type: input
    id: language-name
    attributes:
      label: Language name
    validations:
      required: true
  - type: input
    id: language-code
    attributes:
      label: Language code (LCID)
    validations:
      required: false
  - type: textarea
    id: translation-issue
    attributes:
      label: Describe the issue
    validations:
      required: true
