name: Build

on:
  push:
  pull_request:

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v4
      - name: "Setup: Node"
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: control/package-lock.json
      - name: "Setup: dotnet"
        uses: actions/setup-dotnet@v4
      - name: "Build: dotnet restore"
        run: dotnet restore
      - name: "Build: dotnet build"
        run: dotnet build --no-restore
      - name: "Build: dotnet test"
        run: dotnet test --no-build
      - name: "Artifacts: Create file containing URL of repo"
        run: echo "${{ github.server_url }}/${{ github.repository }}" > ./dist/repo-url.txt
      - name: "Artifacts: Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}__extract_this_zip
          path: ./dist/*
          retention-days: 15
