name: Close inactive issues
on:
  schedule:
    - cron: "30 7 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-label: "Stale"
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-message: "This issue was marked as stale because it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 14 days."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          stale-pr-label: "Stale"
          days-before-pr-stale: 45
          days-before-pr-close: -1
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity.'
          repo-token: ${{ secrets.GITHUB_TOKEN }}